### ISSUE TITLE
NullPointerException when click image

### ISSUE THREAD

**Issue by Aspsine** [googlesamples/android-unsplash#2]
```
FATAL EXCEPTION: main
Process: com.example.android.unsplash, PID: 9273
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.view.View.getTransitionName()' on a null object reference
at com.example.android.unsplash.ui.grid.PhotoAdapter$1.onClick(PhotoAdapter.java:87)
at android.view.View.performClick(View.java:4909)
at android.view.View$PerformClick.run(View.java:20390)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5757)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:799)
```

My phone doesn't has `navigationBar`.  I also tested in Emulator which has a 'navigationBar' and it works fine.

**Comment by yeahia2508** [comment]
Same here. click image in landscape mode causing this problem.

**Comment by 81813780** [comment]
See #3

**Comment by HarlonWang** [comment]
See #3 @yeahia2508

**Comment by ananth10** [comment]
I am also facing same issue . anyone got a idea??

**Comment by yeahia2508** [comment]
Now it's working.. Issue fixed :dancer:

**Comment by ananth10** [comment]
@yeahia2508 how did you fix it?

**Comment by yeahia2508** [comment]
Fixed by @Aspsine . see [#3](https://github.com/googlesamples/android-unsplash/pull/3) and [commit](https://github.com/googlesamples/android-unsplash/pull/3/commits/3a7b22376d5ca903555792d0027e8177c143cd42)

**Comment by ananth10** [comment]
Ya .Its working now @yeahia2508 .
