### ISSUE TITLE
Sometime getting NullPointerException clicking navigation back icon in DetailActivity

### ISSUE THREAD

**Issue by yeahia2508** [googlesamples/android-unsplash#4]
```
    FATAL EXCEPTION: main
    java.lang.NullPointerException
    at com.example.android.unsplash.DetailActivity$1.onSharedElementEnd(DetailActivity.java:69)
    at android.app.ExitTransitionCoordinator.startSharedElementExit(ExitTransitionCoordinator.java:185)
    at android.app.ExitTransitionCoordinator.access$000(ExitTransitionCoordinator.java:43)
    at android.app.ExitTransitionCoordinator$1.run(ExitTransitionCoordinator.java:152)
    at android.app.ActivityTransitionCoordinator.startTransition(ActivityTransitionCoordinator.java:698)
    at android.app.ExitTransitionCoordinator.sharedElementExitBack(ExitTransitionCoordinator.java:150)
    at android.app.ExitTransitionCoordinator.onReceiveResult(ExitTransitionCoordinator.java:111)
    at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5221)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by keyboardsurfer** [comment]
Fixed by #1.
